language: android
jdk: oraclejdk8
dist: trusty

env:
  global:
    - ANDROID_API_LEVEL = 30
    - ANDROID_BUILD_TOOLS_VERSION = 30.0.0
    - ANDRID_EMU_API_LEVEL = 22
    - ANDROID_ABI = armeabi-v7a
    - QEMU_AUDIO_DRV = none

android:
  components:
  #Android sdk tools
  - tools
  - platform-tools
  #build tools version
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  # SDK version
  - android-$ANDROID_API_LEVEL
  - android-$ANDRID_EMU_API_LEVEL

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    # Building the emulator
    - sys-img-$ANDROID_ABI_google_apis-ANDROID_EMU_API_LEVEL
  licenses:
      - 'android-sdk-preview-license-52d11cd2'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

before_install:
- chmod +x gradlew
- yes|sdkmanager "platform;android-$ANDROID_EMU_API_LEVEL"
#- yes|sdkmanager "platform;android-$ANDROID_API_LEVEL"

before_script:

  - echo no | android create avd --force -n test -t android-$ANDROID_EMU_API_LEVEL --abi google-apis/$ANDROID_ABI
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - abd shell input keyevent 82 &
  #add comments
#script:
#  - ./gradlew clean build
#  - ./gradlew test
